name: myenv
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy
  - opencv
  - pillow
  - scikit-image
  - tqdm
  - pip
  - pip:
      - pyzbar
      - imutils
      - torch>=1.7
      - torchvision>=0.8.1
      - ultralytics
